import { Case, Event, Family, Knowledge, Metrics } from "./types";
const policies: Knowledge[] = [
 {id:"p1",type:"POLICY",title:"Shipment integrity",content:"Never cancel or refund shipped items without a specific policy.",family:"partial_shipment_cancellation",source:"seed",confidence:1},
 {id:"p2",type:"POLICY",title:"Replacement control",content:"A dispatched replacement requires an approved return or delivery outcome before refund.",family:"replacement_refund",source:"seed",confidence:1},
 {id:"p3",type:"POLICY",title:"Discount allocation",content:"Partial refunds must allocate an order-level discount proportionally.",family:"discounted_partial_refund",source:"seed",confidence:1}
];
const unknown: Case = {id:"case-001",family:"partial_shipment_cancellation",customer:"Avery Chen",detail:"Three items: two shipped, one backordered. Customer requests cancellation.",status:"NEW",attempts:0,humanUsed:false};
let skills: Knowledge[]=[]; let cases: Case[]=[]; let events: Event[]=[];
export function reset(){skills=[];cases=[];events=[];}
export function seed(){ reset(); cases=[unknown,{id:"case-002",family:"partial_shipment_cancellation",customer:"Jordan Lee",detail:"One item shipped, one awaiting fulfillment. Customer wants to cancel the order.",status:"NEW",attempts:0,humanUsed:false},{id:"case-003",family:"replacement_refund",customer:"Morgan Patel",detail:"Replacement has left the warehouse; customer requests a refund.",status:"NEW",attempts:0,humanUsed:false},{id:"case-004",family:"replacement_refund",customer:"Sam Rivera",detail:"Replacement was dispatched this morning and customer asks for refund.",status:"NEW",attempts:0,humanUsed:false},{id:"case-005",family:"discounted_partial_refund",customer:"Taylor Kim",detail:"Customer requests one-item refund from discounted multi-item order.",status:"NEW",attempts:0,humanUsed:false},{id:"case-006",family:"discounted_partial_refund",customer:"Alex Moore",detail:"Refund one item while allocating an order-level discount.",status:"NEW",attempts:0,humanUsed:false}]; return cases; }
export function addEvent(caseId:string,sender:string,message:string,recipient?:string){events.unshift({id:crypto.randomUUID(),caseId,sender,recipient,message,timestamp:new Date().toISOString()});}
export function retrieve(c:Case){return [...policies.filter(x=>x.family===c.family),...skills.filter(x=>x.family===c.family)].map(x=>({...x, relevance:x.type==="LEARNED_SKILL"?.94:.72}));}
export function learn(family:Family){const skill:Knowledge={id:"skill-"+crypto.randomUUID().slice(0,6),type:"LEARNED_SKILL",title:"Partial shipment cancellation",content:"Keep shipped items. Cancel only unshipped items and refund that item's value.",family,source:"human",confidence:.9};skills.push(skill);return skill;}
export function save(c:Case){const i=cases.findIndex(x=>x.id===c.id);if(i>=0)cases[i]=c;else cases.push(c);}
export const store={get cases(){return cases},get skills(){return skills},get events(){return events},get policies(){return policies}};
export function metrics():Metrics{const total=cases.length||1, resolved=cases.filter(c=>c.status==="RESOLVED");return {total:cases.length,autonomousRate:Math.round(100*resolved.filter(c=>!c.humanUsed).length/total),escalationRate:Math.round(100*cases.filter(c=>c.humanUsed).length/total),correctRate:Math.round(100*resolved.length/total),unsupportedRate:Math.round(100*cases.filter(c=>c.status==="HUMAN_REQUIRED").length/total),avgHuman:+(cases.filter(c=>c.humanUsed).length/total).toFixed(2)};}
